# Project MCS
NoAttachMsg= No attachment found
MAX_INACTIVE_INTERVAL= 1800
# change password functionality
label.PWD.PwdHistory= This password has been set before.Please enter a new password.
label.PWD.kmsMsgOldPwd= Enter old password
label.PWD.kmsMsgNewPwd= Please specify your new password
label.PWD.kmsMsgPwdNotChanged= Your password has not changed. Try again !!!!
label.PWD.kmsMsgCorrectOldPwd= Password Change Failed! Enter correct old password
label.PWD.changePwdTitle= Change Password
label.PWD.oldpassword= Old Password
label.PWD.newpassword= New Password
label.PWD.reenternewpwd= Confirm New Password
label.PWD.saveBtn= Save
label.PWD.cancelBtn= Cancel
label.PWD.resetBtn= Reset
label.PWD.searchBtn= Search
label.PWD.kmsMsgNewPwdNumeric= New password should contain atleast one numeric digit
label.PWD.kmsMsgNewPwdSplChrs= New password should contain atleast one special character
label.PWD.kmsMsgNewPwdChrs= New password should contain atleast one alphabet.
label.PWD.kmsMsgConfirmPwd= Please confirm your New Password entry
label.PWD.kmsMsgNewPwdOldPwd= New password should not be same as the old password
label.PWD.kmspwdspace= Password should not contain spaces
label.PWD.kmsMsgNewPwdMatch= Your new Password entries did not match
label.PWD.kmsMsgPwdLengthVal= Password length should exactly 8  
label.PWD.changePwdSuccessMsg= Password changed successfully. 
label.PWD.pwdSuccess= Password has been changed successfully
label.PWD.emailId.mandatory=Enter email-ID
label.PWD.mobile.mandatory=Enter mobile number
# end change password functionality

# Added for case Search by lakshmi
label.caseSearch.caseSearchTitle = Cases Search
label.caseSearch.claimStatus = Claim Status
label.caseSearch.category= Category
label.caseSearch.errStatus = Erroneous Status
label.caseSearch.caseNo = Case Number
label.caseSearch.claimNo = Claim Number
label.caseSearch.patientName = Patient Name
label.caseSearch.surgeryList = Surgery List
label.caseSearch.wapNo = Card Number
label.caseSearch.claimAmt = Claim Amount
label.caseSearch.regdate =Registered Date
label.EmployeeSearch.prev=prev
label.EmployeeSearch.next=next
label.caseSearch.ErrClaimStatus=Erroneous Status
label.caseSearch.ShowResult=Showing Results
label.caseSearch.of=of
label.caseSearch.ShowPage=Show Page
label.caseSearch.ShowinSet=Show in sets of
label.caseSearch.noResultFnd=No results found
#end
#start of my Profile
label.EmployeeBasicDetails.title=Employee Basic Details 
label.EmployeeBasicDetails.firstName=First Name
label.EmployeeBasicDetails.lastName=Last Name
label.EmployeeBasicDetails.Email=Email
label.EmployeeBasicDetails.fax=Fax
label.EmployeeBasicDetails.LandNumber=Land Line Number
label.EmployeeBasicDetails.MobileNumber=Mobile Number
label.EmployeeBasicDetails.cug=CUG
label.EmployeeBasicDetails.panNumber=PAN card Number
label.EmployeeBasicDetails.qualification=Qualification
label.EmployeeBasicDetails.addr1=Present Address
label.EmployeeBasicDetails.addr2=Permanent Address
label.EmployeeBasicDetails.dob=DOB
label.EmployeeBasicDetails.age=Age

label.EmployeeOtherDetails.title=Employee Other Details
label.EmployeeOtherDetails.gender=Gender
label.EmployeeOtherDetails.male=Male
label.EmployeeOtherDetails.female=Female
label.EmployeeOtherDetails.bloodGroup=Blood Group
label.EmployeeOtherDetails.idMarks=Identity Marks
label.EmployeeOtherDetails.nativeDistrict=Native District
label.EmployeeOtherDetails.religion=Religion
label.EmployeeOtherDetails.mstatus=Marital Status
label.EmployeeOtherDetails.Single=Single
label.EmployeeOtherDetails.Married=Married
label.EmployeeOtherDetails.passPortNo=Passport Number
label.EmployeeOtherDetails.placeOfIssue=Place of Issue
label.EmployeeOtherDetails.expiryDate=Expiry Date
label.EmployeeOtherDetails.drivingLicense=Driving License
label.EmployeeOtherDetails.fatherName=Father Name
label.EmployeeOtherDetails.motherName=Mother Name
label.EmployeeOtherDetails.fatherDOB=Father DOB
label.EmployeeOtherDetails.motherDOB=Mother DOB
label.EmployeeOtherDetails.englishKnows=Knows English
label.EmployeeOtherDetails.teluguKnows=Knows Telugu
label.EmployeeOtherDetails.hindiKnows=Knows Hindi
label.EmployeeOtherDetails.otherKnows=Knows Other Language
label.EmployeeOtherDetails.wordKnows=Knows Word
label.EmployeeOtherDetails.excelKnows=Knows Excel
label.EmployeeOtherDetails.pptKnows=Knows Power Point
label.EmployeeOtherDetails.Yes=Yes
label.EmployeeOtherDetails.No=No
label.EmployeeOtherDetails.community=Community
label.EmployeeOtherDetails.select=---Select---
label.EmployeeOtherDetails.dateOfJoining=Date of Joining
label.AddressDetails.streetNo=Street No.
label.AddressDetails.housetNo=House No.
label.AddressDetails.Dist=Districts
label.AddressDetails.villagertownrcity=Village/Cities/Towns
label.AddressDetails.mandalsrmuncipalities=Mandals/Municpalities
label.AddressDetails.mandalrmuncipality=Mandal/Muncipality
label.AddressDetails.city=City
label.AddressDetails.state=State
label.AddressDetails.country=Country
label.AddressDetails.pin=Pin

# added by lakshmi for past History
label.pastHistory.carUrilizationHis = Card Utilization History
label.pastHistory.caseNo = CaseNo
label.pastHistory.patName=Patient Name
label.pastHistory.regDate=RegDate
label.pastHistory.policyPeriod=Policy Period
label.pastHistory.preauthStat=Preauth Status
label.pastHistory.onBedStat=On Bed Status
label.pastHistory.caseStatus=Case Status
label.pastHistory.claimPaidCost=Claim paid Cost
label.pastHistory.pkgPrice=Pkg price
label.pastHistory.cat=Category
label.pastHistory.subCat=Sub Category
label.pastHistory.therapy=Therapy
label.pastHistory.hospHis=Hospital History
label.pastHistory.nwhDtls=NWH Details
label.pastHistory.nwhName=NWH Name
label.pastHistory.address=Address
label.pastHistory.contactNo=Contact No
label.pastHistory.bedDtls=Bed Details
label.pastHistory.hospBedCap=Hospital Bed Capacity
label.pastHistory.currBedOcc=Current Bed Occupancy
label.pastHistory.specialities=Specialties Empanelled
label.pastHistory.noRecFound =No Records Found

# added by ishank for telephonic Intimation
label.tele.telephonicId=Telephonic ID
label.tele.reg=Registration Date
label.tele.callername=Caller Name
label.tele.callerno=Caller Phone Number
label.tele.district=District
label.tele.callerdistrict=Caller District
label.tele.hosp=Hospital Name
label.tele.Disease=Disease Name
label.tele.doc=Doctor Name
label.tele.docPhNo=Doctor Phone Number
label.tele.caseStatus=Case Status

#added by vasudha for employee search

label.EmployeeSearch.id=Emp/Pensioner ID




label.EmployeeSearch.Name=Name
label.EmployeeSearch.enrollId=Enrolled ID
label.EmployeeSearch.aadhar=Aadhar Number
label.EmployeeSearch.HOD=--HOD--
label.EmployeeData.HOD=HOD
label.EmployeeSearch.select=--Select--
label.EmployeeSearch.District=--District--
label.EmployeeSearch.DDO=--DDO--
label.EmployeeSearch.STODistrict=--District--
label.EmployeeSearch.STO=--STO--
label.EmployeeSearch.EnrollID=Enrolled ID
label.EmployeeSearch.photo=Photo
label.EmployeeSearch.mailId=Mail ID
label.EmployeeSearch.mobile=Mobile Number
label.EmployeeSearch.otherDetails=Other Details
label.EmployeeSearch.ddoOffice=DDO Office
label.EmployeeSearch.stoOffice=STO Office
label.EmployeeSearch.NA=Not Available
label.EmployeeSearch.empCode=Employee Code

#added by vasudha for HOD Report
label.HodReport.HOD=HOD
label.HodReport.District=District
label.HodReport.DDO=DDO
label.HodReport.select=--Select--
label.HodReport.prev=prev
label.HodReport.next=next
label.HodReport.HodReport=HOD Report
label.HodReport.totalSanction=Total Sanctioned Posts
label.HodReport.totalApproved=Total Approved Count
label.HodReport.totalWaiting=Total Wating Count
label.HodReport.totalRejected=Total Rejected Count
label.HodReport.hodId=HOD ID
label.HodReport.hodName=HOD Name
label.HodReport.districtName=District Name
label.HodReport.ddoId=DDO ID
label.HodReport.ddoUnitName=DDO Unit Name
label.HodReport.ddoSanctionPosts=DDO Sanctioned Posts
label.HodReport.watiting=Waiting
label.HodReport.rejected=Rejected
label.HodReport.approved=Approved
label.HodReport.header=Employee Details

#added by vasudha for Card Distribution
label.vendordisplay.empType=Employee Type :
label.vendordisplay.id=Employee-ID/Pensioner-ID:
label.vendordisplay.enrollId=Enroll  Id
label.vendordisplay.loginName=Login Name
label.vendordisplay.district=District
label.vendordisplay.status=Status
label.vendordisplay.registeredDate=Registered Date


#Added by anith for CMS
label.CR.Application.Type=Application Type
label.CR.Organisation.Type=Parent Organisation
label.CR.dept=Department
label.CR.Type=Change Request Type
label.CR.Desc=CR Description
label.CR.dept.Type=Department
label.CR.Title=CR Title
label.CR.SuppDoc=Supporting Documents
label.CR.BuildID.Heading=Change Management>>Build ID Generation
label.CR.BuildID.Date=Build Date
label.CR.BuildID.Desc=Build Description
label.apps.noDocsMsg=No records found
label.apps.CSSAlert= Html,Xml,Javscript tags are not allowed
label.apps.okBtn=OK
label.admin.Company=Company


#card print
label.EHF.Card.Ehs=Employees Health Scheme
label.EHF.Card.TgGovt=Government of Telangana
label.EHF.Card.healthCard=HEALTH CARD
label.EHF.Card.Address=Address
label.EHF.Card.Relation=Relation
label.EHF.Card.DOB=DOB
label.EHF.Card.Pensioner=Pensioner
label.EHF.Card.FamilyPensioner=Family Pensioner
label.EHF.Card.PensionerIdNo=Pensioner ID No.
label.EHF.Card.FamilyPensionerIdNo=Family Pensioner ID No.
label.EHF.Card.Employee=Employee
label.EHF.Card.TemperoryCard=Temporary Card
label.EHF.Card.EmpIdNo=Employee ID No.
label.EHF.Card.DateOfIssue=Date Of Issue
label.EHF.Card.valid=Valid Up To
label.EHF.Card.Till= 
label.EHF.Card.Issued=Issued By
label.EHF.Card.Male=Male
label.EHF.Card.Female=Female
label.EHF.CollectorAndMagistrate=Collector & District Magistrate
label.EHF.District=District
#Relations
label.EHF.Card.Relation.6=Mother
label.EHF.Card.Relation.5=Father
label.EHF.Card.Relation.1=Husband
label.EHF.Card.Relation.2=Wife
label.EHF.Card.Relation.4=Daughter
label.EHF.Card.Relation.3=Son
label.EHF.Card.Relation.8=Grand Daughter
label.EHF.Card.Relation.7=Grand Son
label.EHF.Card.Relation.10=Grand Father
label.EHF.Card.Relation.9=Grand Mother
label.EHF.Card.Relation.14=Mother-In-Law
label.EHF.Card.Relation.13=Father-In-Law
label.EHF.Card.Relation.12=Son-In-Law
label.EHF.Card.Relation.11=Daughter-In-Law
label.EHF.Card.Relation.16=Brother
label.EHF.Card.Relation.17=Sister
label.EHF.Card.Relation.18=Family Head
label.EHF.Card.Relation.0=Self
label.EHF.Card.Relation.15=Others
label.EHF.Card.Dist.SRI=Srikakulam
label.EHF.Card.Dist.VZM=Vizianagaram
label.EHF.Card.Dist.VZG=Visakhapatnam
label.EHF.Card.Dist.EGI=East Godavari
label.EHF.Card.Dist.WGI=West Godavari
label.EHF.Card.Dist.KRS=Krishna
label.EHF.Card.Dist.GNT=Guntur
label.EHF.Card.Dist.PKM=Prakasam
label.EHF.Card.Dist.NLR=Nellore
label.EHF.Card.Dist.CTR=Chittoor
label.EHF.Card.Dist.KDP=Cuddapah
label.EHF.Card.Dist.ANT=Anantapur
label.EHF.Card.Dist.KNL=Kurnool
label.EHF.Card.Dist.MBN=Mahabubnagar
label.EHF.Card.Dist.RRY=Ranga Reddy
label.EHF.Card.Dist.HYD=Hyderabad
label.EHF.Card.Dist.MDK=Medak
label.EHF.Card.Dist.NZD=Nizamabad
label.EHF.Card.Dist.ADB=Adilabad
label.EHF.Card.Dist.KMR=Karimnagar
label.EHF.Card.Dist.WGL=Warangal
label.EHF.Card.Dist.KHM=Khammam
label.EHF.Card.Dist.NLG=Nalgonda


#Added By vasudha for Employee or Pensioner Case search

label.EmpPenCaseSearch.caseId=Case ID
label.EmpPenCaseSearch.CaseName=Case Name
label.EmpPenCaseSearch.patientName=Patient Name
label.EmpPenCaseSearch.hospitalName=Hospital Name
label.EmpPenCaseSearch.CaseStatus=Case Type
label.EmployeeSearch.CaseRegisteredDate=Registered date
label.EmployeeSearch.ProcNames=Procedure
label.EmpPenCaseSearch.CaseFeedback=Feedback
label.EmpPenCaseSearch.ViewAttach=View Attachments
EHF.CaseNo=Case No
EHF.DrugSubTypeNam=Drug Subtype Name
#Added By Ishank for FollowUp
EHF.CardNo=Card No
EHF.FollowUpStatus=FollowUp Status
EHF.FolowUpDate=FollowUp Date
EHF.FollowUpId= FollowUp ID
EHF.Title.FollowUpCaseSearch=Follow Up Cases Search
EHF.Title.FollowUpApproval=Follow Up Cases For Approval
EHF.Title.Journalist.FollowUpCaseSearch=Journalists Follow Up Cases Search
EHF.Title.Journalist.FollowUpApproval=Journalists Follow Up Cases For Approval
EHF.Title.FromDate=From Date
EHF.Title.ToDate=To Date
EHF.Button.Paynow=CD99
EHF.Button.Approve=CD24
EHF.Button.Reject=CD30
EHF.Button.SentBackToCH=CD97
EHF.Button.Msg.SentBackToCH=Do you want to Send Back to CH?
EHF.Button.Msg.Paynow=Do you want to Pay now?
EHF.claim.Status.AccVefied=CD93
EHF.claim.Status.CHVefied=CD96
EHF.Title.AHC= Annual Health Checkup 
label.EHF.Aadhar=Aadhar ID
label.EHF.AadharEid=Aadhar Enrollment ID
label.EHF.State=State

EHF.Title.RegisteredAhcView=REGISTERED AHC VIEW


#common module error message
error.global.message = Due to some issue,your request can't be processed now.Please try again.
