EHF.Title.RegClaim=REGULAR CLAIM
EHF.Title.CosumableDetails=COSUMABLE DETAILS
EHF.Title.DrugDetails=DRUG DETAILS
EHF.Title.NonTech=NON TECHNICAL CHECKLIST
EHF.Claim.DateVerif=Date Verification
EHF.Claim.DocuVerf=Document Verification
EHF.Title.TrustDoc=TRUST DOCTOR CHECKLIST
EHF.Title.Tecnical=TECHNICAL (SPECIALIST) CHECKLIST 
EHF.Title.ClaimHead=Claim Head
EHF.Title.Account=Accounts
EHF.Claim.PackAmt=PreAuth Approved Amount
EHF.Claim.ConsumableAmt=Total Consumable Amount
EHF.Claim.DrugAmt=Total Drug Amount
EHF.Claim.PreAuthDate=Preauth Date
EHF.Claim.PreAuthApprvDate=Preauth Approved Date
EHF.Claim.SubmitDate=Claim Submitted Date
EHF.Claim.NameCaseSheet=1): Name in case sheet and consent forms is correct
EHF.Claim.GenderCaseSheet=2): Gender in case sheet and consent forms is correct
EHF.Claim.BenPhoto=3): Is beneficiary card photo is matching with Discharge Photo and Onbed photo
EHF.Claims.Yes=Yes
EHF.Claims.No=No
EHF.Claim.AdmDate=Admission date
EHF.Claim.SurgDate=Surgery/Therapy date
EHF.Claim.DisDate=Discharge/Death date
EHF.Claim.DocVer1=1): Patient signature is matching across three forms (Counseling form , consent letter and satisfaction letter)
EHF.Claim.DocVer2=2): Patient satisfaction letter feedback is positive
EHF.Claim.DocVer3=4): Mandatory reports are attached
EHF.Claim.DocVer4=3): Reports are signed by doctors with APMC registration number
EHF.Claim.DocVer5=4): Dates and patient name are correctly stated on the reports
EHF.Claim.DocVer6=Remarks:
EHF.Claim.trustDoc1=1)\: Do you agree with remarks of claim panel Doctor? 
EHF.Claim.trustDoc2=2): Is the case management proven to be done as per the standard treatment protocols?
EHF.Claim.trustDoc3=3): Does evidence of the therapy being conducted exist beyond doubts?
EHF.Claim.techCheck1=Total Claim(Rs.)
EHF.Claim.techCheck2=Deduction Recommended (Rs.)
EHF.Claim.techCheck3=Stay (Rs.)
EHF.Claim.techCheck4=Inputs (Rs.)
EHF.Claim.techCheck5=Professional fee bill(s) (Rs.)
EHF.Claim.techCheck6=Investigation Bill(s) (Rs.)
EHF.Claim.techCheck7=1): Diagnosis is supported by evidence
EHF.Claim.techCheck8=2): Case management proven to be done as per the standard treatment protocols
EHF.Claim.techCheck9=3): Evidence of the therapy being conducted exists beyond doubt
EHF.Claims.Role.MEDCO=GP2
EHF.Claims.Role.Mithra=GP1
EHF.Claims.Role.CEX=GP6
EHF.Claims.Role.COCCEX=GP72
EHF.Claims.Role.CPD=GP7
EHF.Claims.Role.HUBS=GP89
EHF.Claims.Role.COCCMT=GP71
EHF.Claims.Role.COCTD=GP73
EHF.Claims.Role.CTD=GP8
EHF.Claims.Role.CH=GP9
EHF.Claims.Role.ACO=GP17
EHF.Claims.Role.CEO=GP40
EHF.Claims.billAmt=Bill Amount
EHF.Claims.billDate=Bill Date
EHF.Claims.FAprAmt=Final Approve Amount
EHF.ErrClaims.Title=Erroneous Claim
EHF.ErrClaims.claimPaid=Claim Paid
EHF.ErrClaims.Amt=Erroneous Amount
EHF.ErrClaims.subDate=Erroneous claim submitted date
EHF.ErrClaims.CTD=Trust Doctor CheckList
EHF.ErrClaims.CH=Claim Head CheckList
EHF.workFlow.title=Work Flow
EHF.workFlow.sno=SNo
EHF.workFlow.Dt=Date & Time
EHF.workFlow.name=Name
EHF.workFlow.role=Role
EHF.workFlow.reamark=Remarks
EHF.workFlow.appAmt=Approve Amount
EHF.workFlow.action=Action
EHF.chronic.claimMsg=Claim is not yet initiated for this Chronic Installment

EHF.Button.Initiate=CD22
EHF.Button.Forward=CD23
EHF.Button.Approve=CD24
EHF.Button.Reject=CD30
EHF.Button.Pending=CD31
EHF.Button.RecmdApp=CD32
EHF.Button.RecmdRej=CD33
EHF.Button.RecmdPend=CD29
EHF.Button.Save=CD71
EHF.Button.Submit=CD72
EHF.Button.Verify=CD73
EHF.Button.initErro=CD74
EHF.Button.SentBackToCH=CD97
EHF.Button.Paynow=CD99
EHF.Button.updateErro=CD129
EHF.Button.update=CD130
EHF.Button.Skip=CD38

EHF.Button.Msg.Initiate=Do you want to Initiate?
EHF.Button.Msg.Forward=Do you want to Forward?
EHF.Button.Msg.Approve=Do you want to Approve?
EHF.Button.Msg.Reject=Do you want to Reject?
EHF.Button.Msg.Pending=Do you want to Pending?
EHF.Button.Msg.RecmdApp=Do you want to Recommend Approve?
EHF.Button.Msg.RecmdRej=Do you want to Recommend Reject?
EHF.Button.Msg.RecmdPend=Do you want to Recommend Pending?
EHF.Button.Msg.Save=Do you want to Save?
EHF.Button.Msg.Submit=Do you want to Submit?
EHF.Button.Msg.Verify=Do you want to Verify?
EHF.Button.Msg.initErro=Do you want to Initiate Erroneous Claim?
EHF.Button.Msg.SentBackToCH=Do you want to Send Back to CH?
EHF.Button.Msg.Paynow=Do you want to Pay now?
EHF.Button.Msg.updateErr=Do you want to Update Erroneous Claim?
EHF.Button.Msg.update=Do you want to Update?
EHF.Button.Msg.skip=Do you want to skip the case?

EHF.title.ClaimPay=Claim Payment
EHF.title.CaseStatus=Case Status
EHF.title.caseNo=Case Number
EHF.title.patientName=Patient Name
EHF.title.fromDte=From Date
EHF.title.toDate=To Date
EHF.title.Search=Search
EHF.title.Reset=Reset
EHF.Info.NoRec=No Record Found
EHF.title.ClaimDtls=Claim Details

EHF.claim.Status.AccVefied=CD93
EHF.claim.Status.CHVefied=CD96
EHF.Claims.Role.EO=GP29
EHF.Claims.Role.EOComm=GP31
EHF.claim.Status.ClaimKeptDiscuCTD=CD119
EHF.claim.Status.DissClearCTD=CD149
EHF.claim.Status.ClaimKeptDiscuCH=CD150
EHF.claim.Status.DissClearCH=CD151
EHF.Button.DiscussionButton=CD118
EHF.Button.ClearButton=CD139
EHF.claim.Status.HubApr=CD758
EHF.claim.Status.HubRej=CD759
EHF.claim.Status.HubPend=CD760

EHF.Claim.ClaimAmt=Claim Amount:
EHF.Claim.MedcoNote= NOTE : 1. Penalty Amount is calculated on the basis of missing Clinical notes.
EHF.Claim.NABH= 2. The Additional Amount for NABH hospitals treating andhra patient will vary based on the final claim package amount approved. 
EHF.Claim.StayRemark=Stay Remarks
EHF.Claim.inputRemark=inputs Remarks
EHF.Claim.ProfRemark=Professional fee bill Remarks
EHF.Claim.InvestRemark=Investigation Bill Remarks
EHF.Claim.EOCheckList=EO CheckList
EHF.Claim.EOCommCheckList=EO Committee CheckList


EHF.Claims.Role.ORGCEX=GP1000
EHF.Claims.Role.ORGCMT=GP1001
EHF.Claims.Role.ORGCTD=GP1002
#Chandana - 6444 - 04-02-2025
HUB_SHARE_OLD=750
SPOKE_SHARE_OLD=1250
HUB_SHARE_NEW=1000
SPOKE_SHARE_NEW=1500
AGENCY_TDS_PERCENTAGE=10
HUB_MAINTENANCE =20
SPOKE_MAINTENANCE=20
DMED_ACOUNT_NAME=DMED MEDICAL SERVICES PVT LTD
DMED_ACOUNT_NO=37069891878
DMED_BANK_ID=1742
