# JDBC and Hibernate Oracle properties
hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
#MYSQL Dialect
#hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.use_sql_comments=false
hibernate.connection.isolation=2
hibernate.jdbc.batch_size=0
#Datasource while deploying in JBOSS
hibernate.connection.datasource=java:/ehfDS
#hibernate.connection.asriDatasource=java:/asriDS
#Datasource while deploying in Tomcat
#hibernate.connection.datasource=java:/comp/env/jdbc/ehfDS
#MYSQL Connection Datasource 
#hibernate.connection.datasource=java:/comp/env/jdbc/ehfDSMYSQL
#hibernate.connection.asriDatasource=java:/comp/env/jdbc/mhssDS
hibernate.connection.release_mode=auto
application.configurations=OperationsTS
application.filearea.dir=/storageNAS-TS-Production/export/file_area/