EHF.Title.PatientRegistration= PATIENT REGISTRATION
EHF.Title.TelephonicPatientRegistration= TELEPHONIC PATIENT REGISTRATION 
EHF.Title.PatientDetails= PATIENT DETAILS
EHF.Title.CaseDetails= CASE DETAILS
#pravalika
EHF.Title.Category=CATEGORY DETAILS
#CR 9043 Admission details
EHF.Title.Admission=ADMISSION DETAILS
EHF.Title.Attachments= ATTACHMENTS
EHF.Title.MedicalDetails= MEDICAL DETAILS
EHF.Title.RegisteredPatientsView= REGISTERED PATIENTS VIEW
EHF.Title.ReportDetails=REPORT DETAILS
EHF.Title.CallerDetails=CALLER DETAILS
EHF.Title.ProvAppDetails=PROVISIONAL APPROVAL DETAILS
EHF.Title.ApprovalBy=PROVISIONAL APPROVAL AUTHORITY DETAILS

EHF.Title.BioRegistration=BIOMETRIC DETAILS
EHF.Title.AdvancedSearch= Advanced Search
EHF.Title.MedicalOncologyHighEndDrugsApprovalRequest=MEDICAL ONCOLOGY HIGH-END DRUGS APPROVAL REQUEST
EHF.Title.MedicalOncologyHighEndDrugsCasesForPreauthInitiation=MEDICAL ONCOLOGY HIGH-END DRUGS CASES FOR PREAUTH INITIATION

EHF.FrameSet.PatientDetails= Patient Details
EHF.NextFollowUp=Next FollowUp Date
EHF.NextFollowUpHead=Next FollowUp Details
EHF.BatchNumber=Batch Number
EHF.DrugExpiryDate=Drug Expiry Date

EHF.Title.InvestDetails= INVESTIGATION DETAILS
EHF.AHC.Package.Statement=Under Annual Health Checkup Package,Patient can take all the Following Investigations
EHF.InvestAttach=Investigation Attachments 
###################################
EHF.IdentificationProof=Identification Document
EHF.MandatoryFields=All fields marked with * are mandatory
EHF.submitEnable=Submit button is enabled only after generating DTRS Form
EHF.Cardtype= Card type
EHF.HealthCardNo= Health Card No
EHF.Employee/PensionerCardNo= Employee/Pensioner Card No
EHF.EmployeeCardNo=Employee Card No
EHF.PensionerCardNo=Pensioner Card No
EHF.JournalistCardNo=Journalist Card No
EHF.RetiredJournalistCardNo=Retired journalist Card No
EHF.NewBornBabyCardNo=New Born Baby
EHF.FamilyHead= Family Head
EHF.CardIssueDate= Card Issue Date
EHF.DateOfBirth= Date Of Birth
EHF.ContactNo= Contact No
EHF.Occupation= Occupation
EHF.Name= Name
EHF.FirstName= First Name
EHF.MiddleName= Middle Name
EHF.LastName= Last Name
EHF.MaritalStatus= Marital Status
EHF.Slab= Slab
EHF.GeneralWard= General Ward
EHF.SemiPrivateWard= Semi Private Ward
EHF.PrivateWard= Private Ward
EHF.Age= Age
EHF.Years= Y
EHF.Months= M
EHF.Days= D
EHF.CardAddress= Card Address
EHF.HouseNo= House No
EHF.Address= Address
EHF.Street= Street
EHF.District= District
EHF.Mdl/Mcl= Mandal/Municipality
EHF.Municipality= Municipality
EHF.Mandal= Mandal
EHF.Village= City/Town/Village
EHF.Hamlet= Hamlet
EHF.Source= Source
EHF.Pin= Pin code
EHF.CommunicationAddress= Communication Address
EHF.SourceNumber= Source Number
EHF.CheckSameAddress= If Card and Communication Address are same 
EHF.Relationship= Relationship
EHF.Select= ---select---
EHF.Date=Date
EHF.Caste=Caste
EHF.Gender=Gender
EHF.Male=Male
EHF.Female=Female
EHF.Child=Child
EHF.GenderList = Male,Female
EHF.All= ALL
EHF.PatientNo= Patient No
EHF.PatientName= Patient Name
EHF.Registration= Registration
EHF.FromDate= From Date
EHF.ToDate= To Date
EHF.RegistrationDate= Registration Date
EHF.Photo= Photo
EHF.RegisteredHospital= Registered Hospital
EHF.TreatmentPlanned= Treatment Dental or not
EHF.PatientRegistration= Patient Registration Form
NoRecordsMsg= No Records Found
EHF.Hospital=Hospital
EHF.DateAndTime= Date and Time of Registration
#pravalika
EHF.Category= Category
EHF.Diagnosis = Provisional Diagnosis
EHF.RegisteredCategory = Registered Category
#end
EHF.ComplaintType= Complaint Type
EHF.ComplaintCode= Complaint Code
EHF.PatientComplaint= Patient Complaint
EHF.PatientComplaintCode= Patient Complaint Code
EHF.HistoryOfPresentIllness= History Of Present illness
EHF.DrugHistory= Drug History
EHF.PastHistory= History Of Past illness
EHF.PersonalHistory= Personal History
EHF.FamilyHistory= Family History
EHF.ExaminationFindings= General Examination Findings
EHF.SystemicExamFnds= SYSTEMIC EXAMINATION
EHF.ProvisionalDiagnosis= Provisional Diagnosis
EHF.PatientDiagnosedby= Patient Diagnosed by
EHF.MEDCO= MEDCO
EHF.InHouseDoctor= In House Doctor
EHF.Consultant= Consultant
EHF.DutyDoctor= DutyDoctor
EHF.DoctorName= Doctor Name
EHF.Doctor.RegistrationNo = Registration No
EHF.doctor.Qualification = Qualification
EHF.GenInvestigations= General Investigations
EHF.Investigations= Investigations
EHF.TestName= Test Name
EHF.Attachment= Attachment
EHF.PatientType= Patient Type
EHF.IP= IP
EHF.OP= OP
EHF.ChronicOP= Chronic OP
EHF.IPNumber= IP Number
EHF.IPNO= IP NO
EHF.AdmissionType= Admission Type
EHF.PropSurgDt= Proposed Surgery Date
EHF.Planned= Planned
EHF.Emergency= Emergency
EHF.AdmissionDate= Admission Date
EHF.FinalDiagnosis= Final Diagnosis
EHF.Diagnosis= Diagnosis
EHF.Therapy= Therapy
EHF.Prescription= Prescription
EHF.OPNO=OP NO
EHF.DateOfOP= Date Of OP
EHF.HospitalName=Hospital Name
EHF.Scheme=Scheme
EHF.AndhraPradesh=Andhra Pradesh
EHF.Telangana=Telangana
#CR 9034 Admission Details pravalika
EHF.AdmissionNote= Admission Note
EHF.EstimatedAmt= Estimated Amount
EHF.Attachments= Admission Attachment
#####################################################
EHF.Helptext.CardIssueDt= Enter Card Issue Date

#####################################################

REPORTS.AgeGrpAll=Below 14, Age 15-25, Age 26-35, Age 36-45, Age 46-55, Age 56-65, Above 65
REPORTS.AgGrp=Age Group
REPORTS.AgeGrp1=Below 14
REPORTS.AgeGrp2=Age 15-25
REPORTS.AgeGrp3=Age 26-35
REPORTS.AgeGrp4=Age 36-45
REPORTS.AgeGrp5=Age 46-55
REPORTS.AgeGrp6=Age 56-65
REPORTS.AgeGrp7=Above 65
REPORTS.AgeGrpList=0-6,6-14

EHF.SNO=S No
EHF.Designation=Designation
EHF.PhoneNo=Phone Number
EHF.CallerName=Caller Name 
EHF.DocName=Name of the Doctor
EHF.DateOfInt=Date and Time of Intimation  
EHF.Remarks=Remarks
EHF.DiagType= Diagnosis Type
EHF.MainCatName= Main Category Name
EHF.CatName= Category Name
EHF.CatCode= Category Code
EHF.SubCatName= Sub Category Name
EHF.DiseaseName= Disease Name
EHF.DisAnatomicalName= Disease Anatomical Name
EHF.DiagCode= Diagnosis Code
EHF.MainCatCode= Main Category Code
EHF.SubCatCode= Sub Category Code
EHF.DiseaseCode= Disease Code
EHF.DisAnatomicalCode= Disease Anatomical Code
EHF.ICDCatName= ICD Category
EHF.ICDSubCatName=ICD Sub Category
EHF.ICDProc= ICD Procedure
EHF.ICDCatCode= ICD Category Code 
EHF.ICDSubCatCode=ICD Sub Category Code
EHF.ICDProcCode= ICD Procedure Code
EHF.ProcCode= Procedure Code
EHF.SurgryName=Surgery
EHF.Indication=Indication for Telephonic Intimation
EHF.DrugTypeName= Drug Type Name
EHF.DrugTypeCode=Drug Type Code
EHF.DrugSubTypeName= Drug Sub Type Name
EHF.DrugSubTypeCode=Drug Sub Type Code
EHF.DrugName= Drug Name
EHF.DrugCode= Drug Code
EHF.Route= Route
EHF.Strength= Strength
EHF.Dosage= Dosage(per day)
EHF.MedicationPeriod= Medication Period(Days)
EHF.BatchNo=Batch Number
EHF.ExpiryDt=Expiry Date
EHF.MainSymptomName= Main Symptom Name
EHF.MainSymptomCode= Main Symptom Code
EHF.SubSymptomName= Sub Symptom Name
EHF.SubSymptomCode= Sub Symptom Code
EHF.SymptomName= Symptom Name
EHF.SymptomCode= Symptom Code
EHF.OpCatName= OP Category Name
EHF.OpCatCode= OP Category Code
EHF.OpPkgName= OP Package Name
EHF.OpPkgCode= OP Package Code
EHF.ICDName= ICD Name
EHF.ICDCode= ICD Code
EHF.CallerNo=Caller Phone Number
EHF.DocPhNo=Doctor Phone Number
EHF.Tele.CaseStatus=Case Status
EHF.CaseNo=Case ID
EHF.CaseType=Case Type

EHF.TelephonicId=Telephonic ID
EHF.Bio.FingerType=Biometric Finger.
EHF.Bio.HandType=Biometric Hand.
EHF.Bio.Cap=CAPTURE BIOMETRICS
###################################################

Preauth.CochImplant=Check List for candidacy for Cochlear Implantation
Preauth.NameOfTheChild=Name of the Child
Preauth.FatherName= Father name
Preauth.AgeOfTheChild=Age of the Child
Preauth.CaseNo=Case No
Preauth.ClaimNo=Claim No
Preauth.NameOfTheNetworkingHospital=Name of the Net working Hospital
Preauth.DateOfCICommitteeAssessment=Date of CI Committee assessment
Preauth.AudiologicalCriterion=Audiological Criterion
Preauth.AgeOfTheOnsetOfTheProblem=Age of the onset of the problem
Preauth.AgeOfTheIntervention=Age of the Intervention
Preauth.HasTheChildUsedConventionalHearingAid=Has the child used conventional hearing aid(s) ?
Preauth.BenefitFromTheUseOfConventionalHearingAid=Benefit from the use of conventional hearing aid(s)
Preauth.DevelopmentOfAnyAuditoryComprehension=Development of any auditory Comprehension
Preauth.AttemptsToCommunicateInOralAuralMethod= Attempts to communicate in oral-aural method
Preauth.DoesTheChildSpeechRead=Does the child speak / read ?
Preauth.AwarenessOfTheMotherAboutTheProblem=Awareness on the part of the mother about the extent and type of hearing problem the child has
Preauth.AwareOfImpTech=Is the mother aware of the importance & the audio-verbal rehabilitation techniques ?
Preauth.MotivSpeech=Motivation on the part of the child to communicate through Speech
Preauth.MotiVerbal=Motivation on the part of the Mother to develop Audio-Verbal skills
Preauth.RealExpct=Realistic expectations of the mother <br> Commitment of the family and other family members
Preauth.MidEarInf=Does the child have any middle ear infections ?
Preauth.IfYesSpecify= If yes Specify
Preauth.CongenAbnorm=Does the child have any other Congenital Abnormalities other than the deafness ?
Preauth.NormalBonyCapsule=Does the child have normal bony capsule of the Cochlear ?
Preauth.NormalMile=Does the Child have normal milestones ?
Preauth.NormSpMech=Does the child have normal speech mechanism ?
Preauth.BehavProb=Does the child have any behavioral problems :<br>   Is the child free from ADHD ?
Preauth.StableBehavr=Does the child have stable, quiet behavior?
Preauth.AutisTend=Does the child have autistic tendencies?
Preauth.StubbornBehavr=Does the child have stubborn behavior ?
Preauth.ImitativBehavr=Does Child exhibit imitative behavior ?
Preauth.RecForFurtherEval=Recommended for further evaluation
Preauth.Member=Member
Preauth.FitOrUnfit=He/She is FIT/UNFIT to under go surgery and follow-up therapy as per guidelines 


###################################################
EHF.Title.AnnualHealthCheckup=ANNUAL HEALTH CHECKUP