IPOP.APCode=S17
IPOP.CmbhdrIDS=CH4~CH11~CH6
IPOP.DistrictHDRID=LH6
IPOP.MandalHDRID=LH7
IPOP.VillageHDRID=LH8
IPOP.HamletHDRID=LH9
IPOP.CasteCMBHDRID=CH6
IPOP.RelationCMBHDRID=CH4
###############################################
Role.Aarogyamithra = CD10
Role.Ramco= CD9
#########################################################
CASE.CaseRegistered = CD73
CASE.OnBed = CD483 
case.RowsPerPage=10
case.StartIndex1=1
case.ShowPage=1
case.next=11
case.StartIndex0=0