tools.dir=/EHS-TS/export/Operations
projects.dir=/workspaces
tcs.lib=${tools.dir}/libs
ExtjsDst.dir=${tools.dir}/extjsnew

CommonComponents.jar=${tcs.lib}/CommonComponents.jar
antlr.jar=${tcs.lib}/antlr-2.7.6.jar
asm.jar=${tcs.lib}/asm-2.2.3.jar
aspectjrt.jar=${tcs.lib}/aspectjrt.jar
cglib-nodep.jar=${tcs.lib}/cglib-nodep-2.1_3.jar
commons-beanutils-1.9.0.jar=${tcs.lib}/commons-beanutils-1.9.0.jar
commons-codec.jar=${tcs.lib}/commons-codec-1.3.jar
commons-collections.jar=${tcs.lib}/commons-collections.jar
commons-configuration.jar=${tcs.lib}/commons-configuration-1.5.jar
commons-dbcp.jar=${tcs.lib}/commons-dbcp.jar
commons-fileupload.jar=${tcs.lib}/commons-fileupload-1.2.jar
commons-logging-1.0.4.jar=${tcs.lib}/commons-logging-1.0.4.jar
commons-io.jar=${tcs.lib}/commons-io-1.4.jar
commons-lang.jar=${tcs.lib}/commons-lang.jar
commons-pool.jar=${tcs.lib}/commons-pool.jar
dom4j.jar=${tcs.lib}/dom4j-1.6.1.jar
hibernate-annotations.jar=${tcs.lib}/hibernate-annotations.jar
hibernate-commons-annotations.jar=${tcs.lib}/hibernate-commons-annotations.jar
hibernate-entitymanager.jar=${tcs.lib}/hibernate-entitymanager.jar
hibernate-validator.jar=${tcs.lib}/hibernate-validator.jar
hibernate3.jar=${tcs.lib}/hibernate3.jar
jasypt.jar=${tcs.lib}/jasypt-1.4.1.jar
jettison.jar=${tcs.lib}/jettison-1.0-RC2.jar
json.jar=${tcs.lib}/json.jar
gson.jar=${tcs.lib}/gson-2.2.2.jar
#SMS Jars
activation-1.1.jar=${tcs.lib}/activation-1.1.jar
axiom-api-1.2.8.jar=${tcs.lib}/axiom-api-1.2.8.jar
axiom-dom-1.2.8.jar=${tcs.lib}/axiom-dom-1.2.8.jar
axiom-impl-1.2.8.jar=${tcs.lib}/axiom-impl-1.2.8.jar
axis2-adb-1.5.1.jar=${tcs.lib}/axis2-adb-1.5.1.jar
axis2-adb-codegen-1.5.1.jar=${tcs.lib}/axis2-adb-codegen-1.5.1.jar
axis2-ant-plugin-1.5.1.jar=${tcs.lib}/axis2-ant-plugin-1.5.1.jar
axis2-clustering-1.5.1.jar=${tcs.lib}/axis2-clustering-1.5.1.jar
axis2-codegen-1.5.1.jar=${tcs.lib}/axis2-codegen-1.5.1.jar
axis2-corba-1.5.1.jar=${tcs.lib}/axis2-corba-1.5.1.jar
axis2-fastinfoset-1.5.1.jar=${tcs.lib}/axis2-fastinfoset-1.5.1.jar
axis2-java2wsdl-1.5.1.jar=${tcs.lib}/axis2-java2wsdl-1.5.1.jar
axis2-jaxbri-1.5.1.jar=${tcs.lib}/axis2-jaxbri-1.5.1.jar
axis2-jaxws-1.5.1.jar=${tcs.lib}/axis2-jaxws-1.5.1.jar
axis2-jibx-1.5.1.jar=${tcs.lib}/axis2-jibx-1.5.1.jar
axis2-json-1.5.1.jar=${tcs.lib}/axis2-json-1.5.1.jar
axis2-kernel-1.5.1.jar=${tcs.lib}/axis2-kernel-1.5.1.jar
axis2-metadata-1.5.1.jar=${tcs.lib}/axis2-metadata-1.5.1.jar
axis2-mtompolicy-1.5.1.jar=${tcs.lib}/axis2-mtompolicy-1.5.1.jar
axis2-saaj-1.5.1.jar=${tcs.lib}/axis2-saaj-1.5.1.jar
axis2-spring-1.5.1.jar=${tcs.lib}/axis2-spring-1.5.1.jar
axis2-transport-http-1.5.1.jar=${tcs.lib}/axis2-transport-http-1.5.1.jar
axis2-transport-local-1.5.1.jar=${tcs.lib}/axis2-transport-local-1.5.1.jar
axis2-xmlbeans-1.5.1.jar=${tcs.lib}/axis2-xmlbeans-1.5.1.jar
bcel-5.1.jar=${tcs.lib}/bcel-5.1.jar
commons-httpclient-3.1.jar=${tcs.lib}/commons-httpclient-3.1.jar
geronimo-annotation_1.0_spec-1.1.jar=${tcs.lib}/geronimo-annotation_1.0_spec-1.1.jar
geronimo-jaxws_2.1_spec-1.0.jar=${tcs.lib}/geronimo-jaxws_2.1_spec-1.0.jar
geronimo-saaj_1.3_spec-1.0.1.jar=${tcs.lib}/geronimo-saaj_1.3_spec-1.0.1.jar
geronimo-stax-api_1.0_spec-1.0.1.jar=${tcs.lib}/geronimo-stax-api_1.0_spec-1.0.1.jar
geronimo-ws-metadata_2.0_spec-1.1.2.jar=${tcs.lib}/geronimo-ws-metadata_2.0_spec-1.1.2.jar
httpcore-4.0.jar=${tcs.lib}/httpcore-4.0.jar
jalopy-1.5rc3.jar=${tcs.lib}/jalopy-1.5rc3.jar
jaxb-api-2.1.jar=${tcs.lib}/jaxb-api-2.1.jar
jaxb-impl-2.1.7.jar=${tcs.lib}/jaxb-impl-2.1.7.jar
jaxb-xjc-2.1.7.jar=${tcs.lib}/jaxb-xjc-2.1.7.jar
jaxen-1.1.1.jar=${tcs.lib}/jaxen-1.1.1.jar
jettison-1.0-RC2.jar=${tcs.lib}/jettison-1.0-RC2.jar
jibx-bind-1.2.1.jar=${tcs.lib}/jibx-bind-1.2.1.jar
jibx-run-1.2.1.jar=${tcs.lib}/jibx-run-1.2.1.jar
mail-1.4.jar=${tcs.lib}/mail-1.4.jar
mex-1.5.1.jar=${tcs.lib}/mex-1.5.1.jar
neethi-2.0.4.jar=${tcs.lib}/neethi-2.0.4.jar
smack-3.0.4.jar=${tcs.lib}/smack-3.0.4.jar
smackx-3.0.4.jar=${tcs.lib}/smackx-3.0.4.jar
soapmonitor-1.5.1.jar=${tcs.lib}/soapmonitor-1.5.1.jar
woden-api-1.0M8.jar=${tcs.lib}/woden-api-1.0M8.jar
woden-impl-dom-1.0M8.jar=${tcs.lib}/woden-impl-dom-1.0M8.jar
wsdl4j-1.6.2.jar=${tcs.lib}/wsdl4j-1.6.2.jar
wstx-asl-3.2.4.jar=${tcs.lib}/wstx-asl-3.2.4.jar
xalan-2.7.1.jar=${tcs.lib}/xalan-2.7.1.jar
xml-resolver-2.11.0.jar=${tcs.lib}/xml-resolver-2.11.0.jar
XmlSchema-1.4.3.jar=${tcs.lib}/XmlSchema-1.4.3.jar
poi-3.10-beta2-20130904.jar=${tcs.lib}/poi-3.10-beta2-20130904.jar
poi-ooxml-3.10-beta2-20130904.jar=${tcs.lib}/poi-ooxml-3.10-beta2-20130904.jar
poi-ooxml-schemas-3.10-beta2-20130904.jar=${tcs.lib}/poi-ooxml-schemas-3.10-beta2-20130904.jar
quartz-all-1.6.0.jar=${tcs.lib}/quartz-all-1.6.0.jar
xmlbeans-2.3.0.jar=${tcs.lib}/xmlbeans-2.3.0.jar
#SMS Jars
jta.jar=${tcs.lib}/jta.jar
log4j.jar=${tcs.lib}/log4j-1.2.14.jar
ojdbc6.jar=${tcs.lib}/ojdbc6.jar
quartz-all.jar=${tcs.lib}/quartz-all-1.6.0.jar
regexp.jar=${tcs.lib}/regexp-1_2.jar
spring-beans.jar=${tcs.lib}/spring-beans.jar
spring-context.jar=${tcs.lib}/spring-context.jar
spring-core.jar=${tcs.lib}/spring-core.jar
spring-jdbc.jar=${tcs.lib}/spring-jdbc.jar
spring-ldap.jar=${tcs.lib}/spring-ldap-1.2.1.jar
spring-modules-jakarta-commons.jar=${tcs.lib}/spring-modules-jakarta-commons.jar
spring-orm.jar=${tcs.lib}/spring-orm.jar
spring-test.jar=${tcs.lib}/spring-test.jar
spring-tx.jar=${tcs.lib}/spring-tx.jar
spring-web.jar=${tcs.lib}/spring-web.jar
spring-webmvc-portlet.jar=${tcs.lib}/spring-webmvc-portlet.jar
spring-webmvc-struts.jar=${tcs.lib}/spring-webmvc-struts.jar
spring-webmvc.jar=${tcs.lib}/spring-webmvc.jar
spring.jar=${tcs.lib}/spring.jar
standard.jar=${tcs.lib}/standard.jar
struts-core.jar=${tcs.lib}/struts-core-1.3.8.jar
struts-el.jar=${tcs.lib}/struts-el-1.3.8.jar
struts-extras.jar=${tcs.lib}/struts-extras-1.3.8.jar
struts-faces.jar=${tcs.lib}/struts-faces-1.3.8.jar
struts-mailreader-dao.jar=${tcs.lib}/struts-mailreader-dao-1.3.8.jar
struts-scripting.jar=${tcs.lib}/struts-scripting-1.3.8.jar
struts-taglib.jar=${tcs.lib}/struts-taglib-1.3.8.jar
struts-tiles.jar=${tcs.lib}/struts-tiles-1.3.8.jar
struts.jar=${tcs.lib}/struts.jar
tcs-mhssFramework.jar=${tcs.lib}/tcs-mhssFramework.jar
velocity.jar=${tcs.lib}/velocity-1.5.jar
xercesImpl-2.11.0.jar=${tcs.lib}/xercesImpl-2.11.0.jar
servlet-api.jar = ${tcs.lib}/servlet-api.jar
ejb3-persistence.jar = ${tcs.lib}/ejb3-persistence.jar
BiomServer.jar = ${tcs.lib}/BiomServer.jar
barbecue-1.5-beta1.jar = ${tcs.lib}/barbecue-1.5-beta1.jar
barcode.jar=${tcs.lib}/barcode.jar
jstl-1.2.jar=${tcs.lib}/jstl-1.2.jar
jxl.jar=${tcs.lib}/jxl.jar
displaytag-1.2.jar=${tcs.lib}/displaytag-1.2.jar
displaytag-portlet-1.2.jar=${tcs.lib}/displaytag-portlet-1.2.jar
displaytag-export-poi-1.2.jar=${tcs.lib}/displaytag-export-poi-1.2.jar
j2ee-1.4.jar=${tcs.lib}/j2ee-1.4.jar
itext-2.1.7.jar=${tcs.lib}/itext-2.1.7.jar
SMSService.jar=${tcs.lib}/SMSService.jar
request-response-time-1.1.0.jar=${tcs.lib}/request-response-time-1.1.0.jar


activation.jar=${tcs.lib}/activation.jar
mailapi.jar=${tcs.lib}/mailapi.jar
smtp.jar=${tcs.lib}/smtp.jar
imap.jar=${tcs.lib}/imap.jar
dsn.jar=${tcs.lib}/dsn.jar


#Spring 3.0 libs

org.springframework.aop-3.1.0.M2.jar=${tcs.lib}/org.springframework.aop-3.1.0.M2.jar
org.springframework.asm-3.1.0.M2.jar=${tcs.lib}/org.springframework.asm-3.1.0.M2.jar
org.springframework.aspects-3.1.0.M2.jar=${tcs.lib}/org.springframework.aspects-3.1.0.M2.jar
org.springframework.beans-3.1.0.M2.jar=${tcs.lib}/org.springframework.beans-3.1.0.M2.jar
org.springframework.context-3.1.0.M2.jar=${tcs.lib}/org.springframework.context-3.1.0.M2.jar
org.springframework.context.support-3.1.0.M2.jar=${tcs.lib}/org.springframework.context.support-3.1.0.M2.jar
org.springframework.core-3.1.0.M2.jar=${tcs.lib}/org.springframework.core-3.1.0.M2.jar
org.springframework.expression-3.1.0.M2.jar=${tcs.lib}/org.springframework.expression-3.1.0.M2.jar
org.springframework.instrument-3.1.0.M2.jar=${tcs.lib}/org.springframework.instrument-3.1.0.M2.jar
org.springframework.instrument.tomcat-3.1.0.M2.jar=${tcs.lib}/org.springframework.instrument.tomcat-3.1.0.M2.jar
org.springframework.jdbc-3.1.0.M2.jar=${tcs.lib}/org.springframework.jdbc-3.1.0.M2.jar
org.springframework.jms-3.1.0.M2.jar=${tcs.lib}/org.springframework.jms-3.1.0.M2.jar
org.springframework.orm-3.1.0.M2.jar=${tcs.lib}/org.springframework.orm-3.1.0.M2.jar
org.springframework.oxm-3.1.0.M2.jar=${tcs.lib}/org.springframework.oxm-3.1.0.M2.jar
org.springframework.test-3.1.0.M2.jar=${tcs.lib}/org.springframework.test-3.1.0.M2.jar
org.springframework.transaction-3.1.0.M2.jar=${tcs.lib}/org.springframework.transaction-3.1.0.M2.jar
org.springframework.web-3.1.0.M2.jar=${tcs.lib}/org.springframework.web-3.1.0.M2.jar
org.springframework.web.portlet-3.1.0.M2.jar=${tcs.lib}/org.springframework.web.portlet-3.1.0.M2.jar
org.springframework.web.servlet-3.1.0.M2.jar=${tcs.lib}/org.springframework.web.servlet-3.1.0.M2.jar
org.springframework.web.struts-3.1.0.M2.jar=${tcs.lib}/org.springframework.web.struts-3.1.0.M2.jar

# BY Mahesh for OPENAM

commons-chain-1.2.jar=${tcs.lib}/commons-chain-1.2.jar
commons-digester-2.1.jar=${tcs.lib}/commons-digester-2.1.jar
commons-validator.jar=${tcs.lib}/commons-validator.jar
dom4j-1.6.1.redhat-6.jar=${tcs.lib}/dom4j-1.6.1.redhat-6.jar
esapiport-2009-26-07.jar=${tcs.lib}/esapiport-2009-26-07.jar
forgerock-util-1.1.0.jar=${tcs.lib}/forgerock-util-1.1.0.jar
mail-1.4.5.jar=${tcs.lib}/mail-1.4.5.jar
openam-dtd-schema-11.0.0.jar=${tcs.lib}/openam-dtd-schema-11.0.0.jar
openam-federation-library-11.0.0.jar=${tcs.lib}/openam-federation-library-11.0.0.jar
openam-jaxrpc-schema-11.0.0.jar=${tcs.lib}/openam-jaxrpc-schema-11.0.0.jar
openam-liberty-schema-11.0.0.jar=${tcs.lib}/openam-liberty-schema-11.0.0.jar
openam-mib-schema-11.0.0.jar=${tcs.lib}/openam-mib-schema-11.0.0.jar
openam-rest-11.0.0.jar=${tcs.lib}/openam-rest-11.0.0.jar
openam-saml2-schema-11.0.0.jar=${tcs.lib}/openam-saml2-schema-11.0.0.jar
openam-shared-11.0.0.jar=${tcs.lib}/openam-shared-11.0.0.jar
openam-wsfederation-schema-11.0.0.jar=${tcs.lib}/openam-wsfederation-schema-11.0.0.jar
openam-xacml3-schema-11.0.0.jar=${tcs.lib}/openam-xacml3-schema-11.0.0.jar
OpenFM-11.0.0.jar=${tcs.lib}/OpenFM-11.0.0.jar
org.apache.commons.fileupload.jar=${tcs.lib}/org.apache.commons.fileupload.jar
relaxngDatatype-20020414.jar=${tcs.lib}/relaxngDatatype-20020414.jar
webservices-api-2009-14-01.jar=${tcs.lib}/webservices-api-2009-14-01.jar
webservices-extra-2008-03-12.jar=${tcs.lib}/webservices-extra-2008-03-12.jar
webservices-extra-api-2003-09-04.jar=${tcs.lib}/webservices-extra-api-2003-09-04.jar
webservices-rt-2009-29-07.jar=${tcs.lib}/webservices-rt-2009-29-07.jar
xml-apis-2.11.0.jar=${tcs.lib}/xml-apis-2.11.0.jar
xml-serializer-2.11.0.jar=${tcs.lib}/xml-serializer-2.11.0.jar
org.springframework.spring-library-3.1.0.M2.libd=${tcs.lib}/org.springframework.spring-library-3.1.0.M2.libd
poi-3.7-20101029.jar=${tcs.lib}/poi-3.7-20101029.jar
poi-ooxml-3.7-20101029.jar=${tcs.lib}/poi-ooxml-3.7-20101029.jar
poi-ooxml-schemas-3.10-beta2-20130904.jar=${tcs.lib}/poi-ooxml-schemas-3.10-beta2-20130904.jar
xml-serializer-2.11.0.jar=${tcs.lib}/xml-serializer-2.11.0.jar
commons-io-1.4.jar=${tcs.lib}/commons-io-1.4.jar


apache-httpcomponents-httpclient.jar=${tcs.lib}/apache-httpcomponents-httpclient.jar
commons-codec-1.9.jar=${tcs.lib}/commons-codec-1.9.jar
commons-logging-1.2.jar=${tcs.lib}/commons-logging-1.2.jar
http-core-4.1.jar=${tcs.lib}/http-core-4.1.jar
compile.debug=true
compile.deprecation=false
compile.optimize=true
source.version=1.6
target.version=1.6
line.coverage=10
branch.coverage=10
<!-- Digital Signature -->
server.jar=${tcs.lib}/server.jar
